name: Deployment pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]
    types: [opened, synchronize]

jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install dependencies
        run: npm install 
      - name: Check style
        run: npm run eslint
      - name: Build
        run: npm run build
      - name: Run tests
        run: npm run test
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Run e2e tests
        run: npm run test:e2e
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
      - name: Trigger deployment
        if: ${{ github.event_name == 'push' && !contains(join(github.event.commits.*.message, ' '), '#skip') }}
        run: curl https://api.render.com/deploy/srv-${{ secrets.RENDER_SERVICE_ID }}?key=${{ secrets.RENDER_API_KEY }}
      - name: Build Failed Discord Notification
        uses: rjstone/discord-webhook-notify@v2
        if: ${{ failure() }}
        with:
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
          username: GitHub Actions Bot
          avatarUrl: https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png
          severity: error
          title: Build Failed - ${{ github.repository }}
          description: |
            **Workflow:** ${{ github.workflow }}
            **Branch:** ${{ github.ref_name }}
            **Event:** ${{ github.event_name }}
          details: |
            **Commit:** `${{ github.sha }}`
            **Message:** ${{ github.event.head_commit.message }}
            **Author:** ${{ github.event.head_commit.author.name }}
            
            [View Failed Run](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})

  tag_release:
    needs: [simple_deployment_pipeline]
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' && !contains(join(github.event.commits.*.message, ' '), '#skip') }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@e528bc2b9628971ce0e6f823f3052d1dcd9d512c
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: patch
          DRY_RUN: false
      - name: Deploy Success Discord Notification
        uses: rjstone/discord-webhook-notify@v2
        if: ${{ success() }}
        with:
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
          username: GitHub Actions Bot
          avatarUrl: https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png
          severity: info
          color: '#22bb33'
          title: New Version Deployed - ${{ github.repository }}
          description: |
            **Version:** ${{ steps.tag_version.outputs.new_tag }}
            **Branch:** ${{ github.ref_name }}
          details: |
            **Commit:** ${{ github.event.head_commit.message }}
            **Author:** ${{ github.event.head_commit.author.name }}
            
            [View Release](https://github.com/${{ github.repository }}/releases/tag/${{ steps.tag_version.outputs.new_tag }})